on: [push]

jobs:
  credentials:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
####----------------------------------------------------------------------------
      ## Updating AWS CLI (latest)
      - name: Updating AWS CLI (lastest)
        id: update_awscli
        env:
          awscli_download: awscli.amazonaws.com
          awscli_platform: linux-x86_64
          awscli_package: awscli-exe-linux-x86_64.zip
        run: |
          aws --version >/dev/null 2>&1 && {
              echo -e >&2 "AWS CLI is Installed ... Ok! ";
              aws --version ;
            } ;
          echo -e "Upgrading AWS-CLI to version 2.0.40" ;
          ## https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2-linux.html
          cd /tmp ;
          wget --quiet "https://${{ env.awscli_download }}/${{ env.awscli_package }}" \
               --directory-prefix=/tmp/ --output-document=awscliv2.zip ;
          unzip awscliv2.zip 1>/dev/null ;
          ls -l /usr/local/bin/aws ;
          sudo ./aws/install --bin-dir /usr/local/bin --install-dir /usr/local/aws-cli --update ;
####----------------------------------------------------------------------------
      ## Inspecting AWS CLI Version
      - name: Inpsecting AWS CLI Version
        id: inspect_awscli
        run: |
          aws --version ;
####----------------------------------------------------------------------------
      - name: Testing AWS STS Assume Role
        uses: ./
        id: request_credentials
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-shared-credentials-file: "${{ github.workspace }}/credentials"
          aws-default-profile: ${{ secrets.AWS_DEFAULT_PROFILE }}
          aws-default-region: ${{ secrets.AWS_DEFAULT_REGION }}
          aws-default-account: ${{ secrets.AWS_DEFAULT_ACCOUNT }}
          session-timestamp: ${{ secrets.SESSION_TIMESTAMP }}
          devops-access-role: ${{ secrets.DEVOPS_ACCESS_ROLE }}
          devops-account-id: ${{ secrets.DEVOPS_ACCOUNT_ID }}
          devops-account-name: ${{ secrets.DEVOPS_ACCOUNT_NAME }}
