on: [push]

jobs:
  credentials:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Testing AWS STS Assume Role
        uses: ./
        id: request_credentials
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-shared-credentials-file: ${{ github.workspace }}
          aws-default-profile: ${{ secrets.AWS_DEFAULT_PROFILE }}
          aws-default-region: ${{ secrets.AWS_DEFAULT_REGION }}
          aws-default-account: ${{ secrets.AWS_DEFAULT_ACCOUNT }}
          session-timestamp: ${{ secrets.SESSION_TIMESTAMP }}
          devops-access-role: ${{ secrets.DEVOPS_ACCESS_ROLE }}
          devops-account-id: ${{ secrets.DEVOPS_ACCOUNT_ID }}
          devops-account-name: ${{ secrets.DEVOPS_ACCOUNT_NAME }}
