on: [push]

env:

  ## AWS Enviroment variables
  AWS_ACCESS_KEYPAIR: ${{ secrets.AWS_ACCESS_KEYPAIR }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  ## AWS Default variables
  AWS_DEFAULT_ACCOUNT: ${{ secrets.AWS_DEFAULT_ACCOUNT }}
  AWS_DEFAULT_PROFILE: ${{ secrets.AWS_DEFAULT_PROFILE }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  ## AWS Shared Credentials file
  AWS_SHARED_CREDENTIALS_FILE: ${{ github.workspace }}/credentials
  ## DevOps environment variables
  DEVOPS_ACCOUNT_NAME: ${{ secrets.DEVOPS_ACCOUNT_NAME }}
  DEVOPS_ACCOUNT_ID: ${{ secrets.DEVOPS_ACCOUNT_ID }}
  DEVOPS_ACCESS_ROLE: ${{ secrets.DEVOPS_ACCESS_ROLE }}

jobs:
  credentials:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
####----------------------------------------------------------------------------
      ## Updating AWS CLI (latest)
      - name: Updating AWS CLI (lastest)
        id: update_awscli
        env:
          awscli_download: awscli.amazonaws.com
          awscli_platform: linux-x86_64
          awscli_package: awscli-exe-linux-x86_64.zip
        run: |
          aws --version >/dev/null 2>&1 && {
              echo -e >&2 "AWS CLI is Installed ... Ok! ";
              aws --version ;
            } ;
          echo -e "Upgrading AWS-CLI to version 2.0.40" ;
          ## https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2-linux.html
          cd /tmp ;
          wget --quiet "https://${{ env.awscli_download }}/${{ env.awscli_package }}" \
               --directory-prefix=/tmp/ --output-document=awscliv2.zip ;
          unzip awscliv2.zip 1>/dev/null ;
          ls -l /usr/local/bin/aws ;
          sudo ./aws/install --bin-dir /usr/local/bin --install-dir /usr/local/aws-cli --update ;
####----------------------------------------------------------------------------
      ## Inspecting AWS CLI Version
      - name: Inpsecting AWS CLI Version
        id: inspect_awscli
        run: |
          aws --version ;
####----------------------------------------------------------------------------
      - name: Testing AWS STS Assume Role
        uses: ./
        id: request_credentials
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-shared-credentials-file: "${{ env.AWS_SHARED_CREDENTIALS_FILE }}"
          aws-default-profile: 'default'
          aws-default-region: 'us-east-1'
          aws-default-account: ${{ env.AWS_DEFAULT_ACCOUNT }}
          session-timestamp: 'DevOpsPipeline20200827193000'
          devops-access-role: ${{ env.DEVOPS_ACCESS_ROLE }}
          devops-account-id: ${{ env.DEVOPS_ACCOUNT_ID }}
          devops-account-name: 'terraform'
